/// # Vector Store Protocol
///
/// Abstraction layer for dense vector storage and similarity search, part of the
/// AI module's semantic search subsystem. Works alongside ``EmbeddingProvider``:
/// embeddings are generated by the provider and stored/searched via the store.
///
/// ## Relationship to Other Components
///
/// - ``EmbeddingProvider`` generates `[Float]` vectors from text (filenames, queries)
/// - ``VectorStore`` stores and searches those vectors keyed by `FileRecord.ID`
/// - ``SearchCoordinator`` (future) combines vector search results with keyword search
///
/// ## Implementations
///
/// - ``FlatFileVectorStore`` — memory-mapped binary file + BNNSVectorSearch from
///   the Accelerate framework. Zero external dependencies. Suitable for up to
///   ~500K vectors on M4.
/// - ``SQLiteVectorStore`` (future) — statically-linked sqlite-vector C extension
///   with quantization support for 1M+ vector scale.
///
/// ## Concurrency
///
/// ``VectorStore`` conforms to `Sendable`. Implementations use actor isolation
/// or internal locking for thread-safe vector storage and retrieval.
///
/// ## Privacy
///
/// All vectors are stored on-device. Vector search never involves network calls
/// or cloud APIs, regardless of which ``EmbeddingProvider`` generated the vectors.
import Foundation
import DeepFinderIndex
import DeepFinderSearch
import DeepFinderPersist

/// Protocol for storing and searching dense vectors (embeddings).
///
/// Each vector is keyed by a `FileRecord.ID` (UInt64). The store supports
/// insert, search (cosine similarity, top-K), delete, and count operations.
///
/// Implementations:
/// - `FlatFileVectorStore` — memory-mapped file + BNNSVectorSearch (zero-dependency)
/// - Future: `SQLiteVectorStore` — sqlite-vector with quantization (vendored C)
///
/// Conforms to `Sendable` for Swift 6 strict concurrency safety.
/// Implementations should use actor isolation or locking for thread-safe storage.
public protocol VectorStore: Sendable {
    /// Insert or update a vector for the given file ID.
    ///
    /// If a vector already exists for this ID, it is replaced.
    /// Vectors must match the dimensionality expected by the store (set at init).
    func insert(id: UInt64, vector: [Float]) async throws

    /// Search for the top-K most similar vectors by cosine similarity.
    ///
    /// Returns results sorted by descending similarity score (1.0 = identical, 0.0 = orthogonal).
    /// Fewer than `topK` results may be returned if the store has fewer entries.
    func search(query: [Float], topK: Int) async throws -> [(id: UInt64, score: Float)]

    /// Remove the vector for the given file ID. No-op if the ID is not present.
    func delete(id: UInt64) async throws

    /// Total number of vectors currently stored.
    func count() async -> Int
}
